kind: Service
apiVersion: v1
metadata:
  name: {{ include "helm_shop.fullname" . }}-srv
spec:
  selector: {{- include "helm_shop.selectorLabels" . | nindent 4 }}
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: {{ .Values.service.type }}
