
kind: Service
apiVersion: v1
metadata:
  name: {{ include "helm_shop.fullname" . }}-srv
spec:
  selector:
    pod: django-container
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: NodePort
